import os
from dotenv import load_dotenv
load_dotenv()

MAX_YT_SEARCH_RESULTS = 20
BATCH_MAX_YT_SEARCH_RESULTS = 5

CLIENT_ID = os.getenv('CLIENT_ID')
CLIENT_SECRET = os.getenv('CLIENT_SECRET')
API_KEY = os.getenv('API_KEY')
PORT = os.getenv('PORT')

API_NAME = 'youtube'
API_VERSION = 'v3'
API_BASE_URL = 'https://youtube.googleapis.com'

VIDEOS_RULE = 'videos'
SEARCH_RULE = 'search'
CHANNEL_RULE = 'channels'

YT_VIDEO_LINK = f'{API_BASE_URL}/{API_NAME}/{API_VERSION}/{VIDEOS_RULE}'
YT_SEARCH_LINK = f'{API_BASE_URL}/{API_NAME}/{API_VERSION}/{SEARCH_RULE}'
YT_CHANNEL_LINK = f'{API_BASE_URL}/{API_NAME}/{API_VERSION}/{CHANNEL_RULE}'

OAUTH_API_NAME = 'oauth2'

USER_INFO_RULE = 'userinfo'

USER_INFO_LINK = f'{API_BASE_URL}/{OAUTH_API_NAME}/{API_VERSION}/{USER_INFO_RULE}'